### ISSUE TITLE
[be/trading-engine] Emit event reflecting changes of the order book after the matching process for an order

### ISSUE THREAD

**Issue by ngocson1** [beesEX/be#13]
This task replaces #4!!!

Summary:
* When order actions (place, update, cancel) have been processed by order service successfully, order events are then created accordingly, these events are sent to trading engine for matching.
* To notify other modules about changes of the order book, the trading engine emits an event each time the matching process for an order executed. The event will be emitted **AFTER** the matching process. It constains all changes made in the matching process.
* The **orderbookevent** has the following structure:
```javascript
 {
          type: 'ORDER_BOOK_EVENT',
          symbol, // we don't need to work with single currency of the pair, just want to identify the market
          reason,
          matches: [match, ...],
          filledCompletely: true|false, // whether order has been filled completely with this event
          timestamp
}
```
* The **reason** object contains the information about the cause triggered the orderbookevent, it can be one of the three structures
```javascript 
{
          type: 'PLACED',
          orderId, // id of the order being processed which triggers this event
          userId,
          side: 'BUY', //'SELL'
          currency,
          baseCurrency,
          price, // if price field is null or undefined, means it is a market order
          quantity
}
{
          type: 'UPDATED',
          orderId, // id of the order being processed which triggers this event
          userId,
          side: 'BUY', //'SELL'
          currency,
          baseCurrency,
          price,
          oldPrice,
          quantity,
          oldQuantity,
          filledQuantity // currently filled quantity of the updated order, before matching
 }
{
          type: 'CANCELED',
          orderId, // id of the order being processed which triggers this event
          userId,
          side: 'BUY', //'SELL'
          currency,
          baseCurrency,
          price,
          quantity,
          filledQuantity // currently filled quantity of the canceled order, before matching
 }
```
* Every **match** object contains the information about one matched order found on counter book side while matching process
```javascript
{
          orderId, // id of the matched order on counter book side
          userId,
          price,
          quantity,
          tradedQuantity, // quantity filled by this match
          filledCompletely: true|false // whether the matched order has been filled completely with this event
 }
```
TODO:
- The trading engine emits one event with the structure described above after every matching process. These events will be processed by both UI - to update the volume-aggregated order book and BE - by order service to update status of orders and trade execution service to execute trades triggered by the matches.
- orderbook childprocess needs to send the events to parent process first, because only parent process has access to the zeroMQ pub-socket to publish these events to UI.
- beesV8 in parent process receives these events from orderbook childprocess and should then use **src/util/zeroMQpublisher.js** to publish all the above orderbook events under topic '**Orderbook-symbol**'
to UI.

Remark:
* **OrderPlacedEvent**, **OrderUpdatedEvent**, **OrderCanceledEvent** defined in #11  can be useful for other purposes.
* The above event is sufficient to update the aggregated order book state on the client side ( browser).
* **OrderCompletelyFilledEvent**, **MarketOrderRejectedEvent**  defined in #4 are no more needed because the information about if an order is completely filled can be extracted from reason and match objects of the above event.

**Comment by tunggad** [comment]
ok, it may work this way but it is complicated and violates many rules of Event Sourcing paradigm:

1. the event in the described structure and when it is emitted does not really represent a **well-defined real business event of the business domain** (crypto exchange platform), it's rather an _artificial_ event which aggregates/combines a series of real business events (matches, order/-place, -update, -cancel). The handling logic of this event to update the aggregated order book on UI, at the first place, may seem to be simpler than having multiple separate handling logic for every single real business events, but i can imagine, that it will be harder to read, understand and maintain than having multiple simple handling logic for every single real events, because to understand the handling logic of this event you really need a deep background of the event structure and how it is built and how it represents information, for example: the field 'filledQuantity' in reason and in match objects, it is named filledQuantity, but it means to be the _filled quantity before the matching process_, i know i could work that way, but it just feels unnatural somehow.

2. the **reason** objects are actually another form of the three order events (OrderPlacedEvent, OrderUpdatedEvent, OrderCanceledEvent), it's object structure does not feel natural, it is primary designed to represent order update event somehow, but it should represent the other two events - order update and cancel, too. In this case these naming of the fields 'originalQuantity', 'originalPrice' are somehow odd, and the fields 'updatedQuantity' and 'updatedPrice' are then null or not undefined. of course, you could model three different object structures for the reason objects in each case, but then they would be exact the same three order events (OrderPlacedEvent, OrderUpdatedEvent, OrderCanceledEvent) as proposed in my approach.

3. you also agree with the idea of the three order events (OrderPlacedEvent, OrderUpdatedEvent, OrderCanceledEvent), that they may be useful for other purposes, so why do not use them now, to update the state of the aggregated order book on UI, instead of creating a new special event for updating the aggregated order book. Event Sourcing paradigm recommends that all system components should try to use the same real business events most of the time consitently, because that gives the system the property called 'conceptual integrity', than having special events for own purposes of each component.

**Comment by ngocson1** [comment]
to 3: 
* Only because they are useful for **other** purposes, it doesn't mean that we should use them everywhere, even where they doesn't fit into.
* Imagine, an placed order buying 100 BTC matches with 100 other orders with quantity 1, how many events the trading engine has to create. Furthermore these events propagate all the way through the backend, the message queue, the ui server, the websocket to the browser.

to 2:  It is true that the reason object was designed to be the union of the three order events (OrderPlacedEvent, OrderUpdatedEvent, OrderCanceledEvent) and it is a bad design but it's structure
is not static. It means we can use 3 different structures representing 3 different kinds of orders.

to 1: 
* An event should reflect changes of the state of a system in an atomic way. The matching process of the trading engine for an order is atomic. It means there are only 2 states of the order book: one before and one after the matching. So an event can only occur accordingly before or after the matching.
* Does the aggregated order book component on the browser need to know about if an order is placed, updated or cancelled? Or it just needs to know how to change it's state from one to another with the minimal overhead.

**Comment by tunggad** [comment]
> Does the aggregated order book component on the browser need to know about if an order is placed, updated or cancelled? Or it just needs to know how to change it's state from one to another with the minimal overhead.

ok. let try to simulate the handling logic of the aggregated order book by comsuming the order events and orderbook event like i suggested:

1. ui gets current aggregated state of orderbook
2. new order placed -> orderplacedevent emitted by order service -> ui received orderplacedevent -> ui increases total volume by quantity at price level of new order
3. new market order placed -> orderplacedevent emitted by order service -> ui received orderplacedevent -> ui increases total volume by quantity at price level of new market order
4. orderbook find a match -> ordermatchevent emitted by orderbook -> ui received ordermatchevent -> ui increases filled volume of both sides by tradedQuantity of the match. ( the same event also goes into trade execution service for settlement)
4. orderbook find a match -> ordermatchevent emitted by orderbook -> ui received ordermatchevent -> ui increases filled volume of both sides by tradedQuantity of the match. ( the same event also goes into trade execution service for settlement)
4. orderbook find a match -> ordermatchevent emitted by orderbook -> ui received ordermatchevent -> ui increases filled volume of both sides by tradedQuantity of the match. ( the same event also goes into trade execution service for settlement)
5. an order has been matched completely -> it is taken from orderbook -> ordercompletelymatchedevent is emitted by orderbook -> ui received ordercompletelymatchedevent -> ui decreases both total volume by quantity and filled volume by filledQuantity at price level of order
6. a market order (with/without remaining quantity) is rejected -> marketorderrejectedevent emitted by orderbook -> ui received marketorderrejectedevent -> ui decreases total volume by quantity and filled volume by filledQuantity at price level of the market order (the same event also goes into order service which changes status of the market order to CLOSED)
7. an open order has been canceled -> ordercanceledevent emitted by order service -> ui received ordercanceledevent -> ui decreases total volume by quantity and filled volume by filledQuantity at price level of the canceled order.
8. an open order has been updated -> orderupdatedevent emitted by order service -> ui received orderupdatedevent -> in case if price delta = 0 (price stays the same), ui increases/decreases total volume by qtyDelta at price level
9. an open order has been updated -> orderupdatedevent emitted by order service -> ui received orderupdatedevent -> in case if price delta != 0 (price updated), ui decreases total volume and filled volume by filledQuantity at old price level (price +/- priceDelta), ui increases total volume by quantity at price level of the updated order

See, how the order events and the orderbook events are perfect fit to maintain the state of the aggregated orderbook on UI.

> Imagine, an placed order buying 100 BTC matches with 100 other orders with quantity 1, how many events the trading engine has to create. Furthermore these events propagate all the way through the backend, the message queue, the ui server, the websocket to the browser

Yeahh, but this is the way an event-driven works, it has technologies helping it to perform well. To name the fews: non-blocking IO of nodejs, zeroMQ, websocket. These technologies are designed to support systems of this architecture style.

> An event should reflect changes of the state of a system in an atomic way. The matching process of the trading engine for an order is atomic. It means there are only 2 states of the order book: one before and one after the matching. So an event can only occur accordingly before or after the matching.

**An event should reflect changes of the state of a system in an atomic way** - yeahh, you say that, your events do not reflect atomic changes, it comprises a series of atomic changes of the system: e.g. new order placed event, a series of matches, this can not be a single atomic change, it is a series of atomic changes, real business events in most case reflect atomic changes of the system.


Son, i really don't know how i can convince you with words :-) But we all get better through discussion like that. happy democratic software dev!!! :-)

**Comment by ngocson1** [comment]
> An event should reflect changes of the state of a system in an atomic way - yeahh, you say that, your events do not reflect atomic changes, it comprises a series of atomic changes of the system: e.g. new order placed event, a series of matches, this can not be a single atomic change, it is a series of atomic changes, real business events in most case reflect atomic changes of the system.

* Every time the trading engine runs the matching process triggered by a placed, cancelled or updated order, it is atomic (transactional), even if there are more than 1 matches because it can't be stop until it has finished.
* Atomic means: STATE x EVENT -> NEW STATE
* Your solution suggests something like this: STATE x EVENT_1 x EVENT_2 x ... x EVENT_x = NEW STATE

> Yeahh, but this is the way an event-driven works, it has technologies helping it to perform well. To name the fews: non-blocking IO of nodejs, zeroMQ, websocket. These technologies are designed to support systems of this architecture style.

No. Not really. Those technologies support the event-driven architecture but they won't help you solve the performance problem caused by sending many small events instead of one big event. Like java helps you manage the memory, but if you don't write a performance application, the app is still slow.

> ok. let try to simulate the handling logic of the ....

 I never said, that your solution is wrong. It is correct but it has a performance problem.

> But we all get better through discussion like 
Yeah, we do. At least our english. 

>happy democratic software dev
No. There is no democracy in software dev. Democracy suggests that a bad solution will be good if the majority believes so. A solution is only good if you can prove it or ... your boss says so.

**Comment by tunggad** [comment]
> Every time the trading engine runs the matching process triggered by a placed, cancelled or updated order, it is atomic (transactional), even if there are more than 1 matches because it can't be stop until it has finished.

ok, i think you convinced me with this point, the matching process of the trading engine triggered by an order event is an atomic process, it's not stoppable at the middle, util it has finished, and all state changes through that process should be captured by a single event -> that's true, i'm convinced.

So i think, we will basically do your solution, take a look at main task description above, i have added some minor updates/improvements

**Comment by hovietanh1991** [comment]
Nice discussion guys. I don't have much experience of software architect and applying theory. But I agree with Son about performance. It will reduce stress on UI server to process events.

**Comment by ngocson1** [comment]
* If orderFilledCompletely: true|false indicates that the **reason** order is filled completely, then we shouldn't put it in the match object, because the match object represents exclusively a matched order on the opposite side. We should put it direct in the event object
```javascript
 {
          type: 'ORDER_BOOK_EVENT',
          symbol, // we don't need to work with single currency of the pair, just want to identify the market
          reason,
          matches: [match, ...],
          timestamp,
          reasonOrderFilledCompletely: true|false
}
```
* In the structure of the reason object for updated order we should use **newPrice**  and **newQuantity** instead of **priceDelta** and **quantityDelta** because:
  * We already have  **newPrice**  and **newQuantity** input by the user
  * If we use **priceDelta** and **quantityDelta** 
    * the trading has to calculate them e.g. **priceDelta** = **price** - **newPrice**
    * then the aggregated order book component on the browser has to calculate the **newPrice** = **price** + **priceDelta** again. Same for **quantity**.

**Comment by hovietanh1991** [comment]
I will close this task for now. If you find any bug, please reopen and provide some info

**Comment by hovietanh1991** [comment]
Because settlement needs also user ID of reason object and match objects in order to call transaction (task #7), I want to reopen this issue to add userId as property of reason and match objects.

**Comment by hovietanh1991** [comment]
also currency and/or base currency are needed

**Comment by hovietanh1991** [comment]
Added userId, currency and baseCurrency for reason object. Added userId for match object.

**Comment by hovietanh1991** [comment]
Update order book structure:
- **Order book event** :
```
order book event = {
  type: "ORDER_BOOK_EVENT",
  symbol, // <currency>_<baseCurrency> e.g. "BTC_USDT"
  reason, // reason object
  ohlcvData, // ohlcv data object
  matches, // array of match object e.g. [ matchObject 0, ..., matchObject n]
  filledCompletely, // boolean: determines reason order (in reason object) is filled completely or not
  timestamp, // time stamp when this order book event was created
}
```
- **Reason object**: there are 3 types of reason object according to 3 types of order:
    - When order type is "LIMIT_PLACE" or "MARKET_PLACE":
    ```
    reason object = {
        type: 'PLACED',
        orderId, // id of order
        userId, // id of user who placed this order
        side, // "SELL" or "BUY"
        currency,
        baseCurrency,
        price,
        quantity
      }
    ```
    - When order type is "CANCEL":
    ```
    reason object = {
        type: "CANCELED",
        orderId, // id of order
        userId, // id of user who placed this order
        side, // "SELL" or "BUY"
        currency,
        baseCurrency,
        price,
        quantity,
        filledQuantity
      }
    ```
    - When order type is "QUANTITY_UPDATE" or "LIMIT_UPDATE":
    ```
    reason object = {
        type: "UPDATED",
        orderId, // id of order
        userId, // id of user who placed this order
        side, // "SELL" or "BUY"
        currency,
        baseCurrency,
        price, // price after updating
        oldPrice, // price before updating
        quantity,  // quantity after updating
        oldQuantity, // quantity before updating
        filledQuantity
      }
    ```
- **OHLCV data object**: contain information of prices and volume
```
OHLCV data object = {
  open, // open price (price of first match object)
  high, // highest price of prices of all match objects
  low, // lowest price of prices of all match objects
  close, // close price (price of last match object)
  volume, // total volume of trades (sum of traded quantity of all match objects)
  time // time of first match, also time of this data in Linux TS (ms)
}
```
- **Match object**: 
```
match object = {
  orderId, // id of order
  userId, // id of user who placed this order
  price,
  quantity,
  tradedQuantity, // the quantity traded with reason order
  filledCompletely, // boolean: determines this match order is filled completely or not
  matchedAt, // time stamp of this match
}
```
