### ISSUE TITLE
[be/settlment] Joi schema validation for Trades collection & tradeexecution service inserts one Trade record for each match executed

### ISSUE THREAD

**Issue by tunggad** [beesEX/be#21]
Summary:
After tradexecution service has performed settlement for the matches, it has to document these trades in DB. That's the mission of the `Trades` collection. Each executed match has to documented by one `Trade` record in DB. And as usual we always validate DB records against some Joi schema.

TODO:
- create Joi schema under `src/settlement/trade.schema.js`
- tradeexecution service has to insert one Trade record for each match whose settlement has been executed successfully

Hint: consult Trade entity in [domain design doc](https://github.com/beesEX/doc/blob/master/documents/beesEX_domain_design.jpeg) for details

**Comment by hovietanh1991** [comment]
update new structure of trade object:
```
trade object = {
  _id, // unique id of trade object
  currency,
  baseCurrency,
  price,
  quantity,
  makerSide, // 'SELL' or 'BUY'
  buyerFeePercent, //currently = 0
  buyerFeeCharged, //currently = 0
  sellerFeePercent, //currently = 0
  sellerFeeCharged, //currently = 0
  createdAt, // created time stamp
  executedAt, // executed time stamp
  matchedAt, // time stamp of match
  buyOrderId, // id of buy order
  sellOrderId // id of sell order
}
```
